# Generated by Django 5.1.6 on 2025-03-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection_app', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppScanSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_apps_scanned', models.IntegerField(default=0, help_text='Total number of apps scanned')),
                ('threats_detected', models.IntegerField(default=0, help_text='Total threats detected across scans')),
                ('community_reports', models.IntegerField(default=0, help_text='Number of reports from the community')),
            ],
        ),
    ]
