# Generated by Django 5.1.6 on 2025-03-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud_detection_app', '0003_appscansummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAppSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(help_text='Name of the application', max_length=255)),
                ('app_image', models.ImageField(help_text='App logo or image', upload_to='images/')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Timestamp of the last activity')),
            ],
        ),
        migrations.CreateModel(
            name='SafeAppSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(help_text='Name of the application', max_length=255)),
                ('app_image', models.ImageField(help_text='App logo or image', upload_to='images/')),
                ('last_activity', models.DateTimeField(auto_now=True, help_text='Timestamp of the last activity')),
            ],
        ),
    ]
